version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: ceedn
      POSTGRES_PASSWORD: ceedn 
      POSTGRES_DB: ceedn-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ceedn"]
      interval: 10s
      retries: 5
      start_period: 30s

  account_manager:
    build: .
    depends_on:
      database:
        condition: service_healthy
    environment:
      - DB_URL=postgresql://ceedn:ceedn@127.0.0.1/ceedn-dev
      - DB_INIT=True
    ports:
      - "8080:8080"