version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ceedn
      POSTGRES_PASSWORD: ceedn 
      POSTGRES_DB: ceedn
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ceedn"]
      interval: 10s
      retries: 5
      start_period: 30s

  account_manager:
    build: .
    depends_on:
      - database
    environment:
      - DB_URL=postgresql://ceedn:ceedn@database/ceedn
      - DB_INIT=True
    ports:
      - "8080:8080"
    links:
      - database
    develop:
      watch:
        - action: rebuild
          path: requirements.txt
        - action: sync
          path: ./acm
          target: /app
