name: Build and publish a Docker image to Harbor
on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [published]
  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: packages.acfc.dev
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag image
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build -t ${{ github.repository }}:$COMMIT_SHA .
          docker tag ${{ github.repository }}:$COMMIT_SHA packages.acfc.dev/library/${{ github.repository }}:latest

      - name: Push image to Harbor
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker push packages.acfc.dev/library/${{ github.repository }}:$COMMIT_SHA
          docker push packages.acfc.dev/library/${{ github.repository }}:latest
