name: Build and publish a Docker image to Harbor
on:
  push:
    branches:
      - main
      - development
    tags:
      - '*'
  pull_request:
    types: [opened, synchronize]
  release:
    types: [published]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: packages.acfc.dev
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and tag image
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          DOCKER_TAG=""
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            DOCKER_TAG="latest"
          elif [[ ${{ github.ref }} == 'refs/heads/development' ]]; then
            DOCKER_TAG="dev"
          elif [[ ${{ github.event_name }} == 'release' ]]; then
            DOCKER_TAG="stable"
          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
            DOCKER_TAG="${{ github.head_ref }}"
          fi
          docker build -t ${{ github.repository }}:$COMMIT_SHA .
          docker tag ${{ github.repository }}:$COMMIT_SHA ${{ github.repository }}:$DOCKER_TAG

      - name: Push image to Harbor
        run: |
          COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          DOCKER_TAG=""
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            DOCKER_TAG="latest"
          elif [[ ${{ github.ref }} == 'refs/heads/development' ]]; then
            DOCKER_TAG="dev"
          elif [[ ${{ github.event_name }} == 'release' ]]; then
            DOCKER_TAG="stable"
          elif [[ ${{ github.event_name }} == 'pull_request' ]]; then
            DOCKER_TAG="${{ github.head_ref }}"
          fi
          docker push packages.acfc.dev/library/${{ github.repository }}:$COMMIT_SHA
          docker push packages.acfc.dev/library/${{ github.repository }}:$DOCKER_TAG
